export const MODULE_PERMISSIONS = [
  {
    name: 'messaging.conversations.create',
    description: 'messaging.conversations.create',
  },
  {
    name: 'messaging.conversations.read',
    description: 'messaging.conversations.read',
  },
  { name: 'messaging.messages.send', description: 'messaging.messages.send' },
  { name: 'messaging.messages.read', description: 'messaging.messages.read' },
  { name: 'messaging.keys.manage', description: 'messaging.keys.manage' },
  { name: 'messaging.presence.read', description: 'messaging.presence.read' },
  {
    name: 'messaging.presence.update',
    description: 'messaging.presence.update',
  },
  { name: 'messaging.admin.read', description: 'messaging.admin.read' },
  { name: 'services.read', description: 'List/read municipal services' },
  { name: 'services.create', description: 'Create municipal services' },
  { name: 'services.update', description: 'Update municipal services' },
  { name: 'services.delete', description: 'Delete municipal services' },
  { name: 'news.read', description: 'List/read municipal publications' },
  { name: 'news.create', description: 'Create municipal publications' },
  { name: 'news.update', description: 'Update municipal publications' },
  { name: 'news.delete', description: 'Delete municipal publications' },
  { name: 'contact.read', description: 'List/read contact messages' },
  { name: 'contact.update', description: 'Update contact messages' },
  { name: 'requests.create', description: 'Submit a citizen request' },
  { name: 'requests.read', description: 'List/read citizen requests' },
  { name: 'requests.update', description: 'Update citizen requests' },
  { name: 'dashboard.read', description: 'Read platform dashboard statistics' },
  { name: 'nova-terra.read', description: 'Read data from the Nova Terra API' },
];
